spring.application.name=financeiro
# Default URL for local development (IntelliJ/localhost)
spring.datasource.url=jdbc:mysql://localhost:3306/pedidos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:010101}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
